all:  fork_q1 fork_q2 fork_q3

fork_q1:
	gcc fork-question-1.c -o fork1

fork_q2:
	gcc fork-question-2.c -o fork2

fork_q3:
	gcc fork-question-3.c -o fork3

clean:
	rm -f fork1
	rm -f fork2
	rm -f fork3
